// Builds docs/API.md from the exported zod schemas, the limits and the i18n strings, with one
// example taken from a real run of the handlers on data/corpus. Nothing in the document is typed
// by hand beyond the prose around the generated parts, so it cannot drift from the code:
// scripts/lib/api-doc.test.ts fails when docs/API.md is not what this file produces.
import { z } from "zod";
import { REVIEW_LIMITS, WARNINGS } from "../../src/core/review.js";
import { REASON_CODES } from "../../src/core/status/index.js";
import { API_ERROR_CODES, ApiErrorSchema, HealthSchema, ReviewRequestSchema, ReviewResultSchema, STATUSES } from "../../src/core/types.js";
import { ar, t, type MessageKey } from "../../src/i18n/ar.js";
import { API_DEFAULTS } from "../../src/server/api-config.js";
import { API_ERROR_HTTP_STATUS, createHealthHandler, createReviewHandler, type ApiDeps } from "../../src/server/api-handlers.js";
import { loadCorpus } from "../../src/server/corpus-loader.js";
import { createRateLimiter } from "../../src/server/rate-limit.js";

export const API_DOC_PATH = "docs/API.md";

// The request of the example. Test input written for this document.
const EXAMPLE_DRAFT = "قال تعالى: ﴿إن الله مع الصابرين﴾ [البقرة: 153]. وقال رسول الله ﷺ: «إنما الأعمال بالنيات».";

const code = (lang: string, text: string): string => `\`\`\`${lang}\n${text}\n\`\`\``;
const jsonBlock = (value: unknown): string => code("json", JSON.stringify(value, null, 2));
const schemaBlock = (schema: z.ZodType): string => jsonBlock(z.toJSONSchema(schema, { io: "output", unrepresentable: "any" }));
const table = (head: string[], rows: string[][]): string =>
  [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`, ...rows.map((row) => `| ${row.join(" | ")} |`)].join("\n");

const WARNING_NOTES: Readonly<Record<keyof typeof WARNINGS, string>> = {
  LLM_UNAVAILABLE_REGEX_ONLY:
    "No LLM took part (none is configured, or its call failed or timed out): the quotes were found by the regex extractor alone, and no explanation was generated.",
  LLM_SPAN_NOT_IN_DRAFT: "The LLM returned at least one quote that the draft does not hold. It was dropped and is not among the items.",
  NOT_A_DRAFT: "The input reads as a request to the tool, not as a draft, and no quote was found in it: `items` is empty.",
  ITEM_LIMIT_REACHED: "The draft holds more quotes than the item limit. The later quotes were not reviewed.",
};

export async function renderApiDoc(root: string): Promise<string> {
  // A real run: the handlers of the routes, on the corpus in data/corpus, with the default settings.
  const deps: ApiDeps = {
    loadCorpus: () => loadCorpus(root),
    config: () => ({ maxDraftChars: API_DEFAULTS.MAX_DRAFT_CHARS, rateLimitPerMin: API_DEFAULTS.RATE_LIMIT_PER_MIN, corsAllowlist: [], llmConfigured: false }),
    log: () => {},
    now: () => 0,
    rateLimiter: createRateLimiter(() => 0),
    newRequestId: () => "example",
  };
  const request = ReviewRequestSchema.parse({ text: EXAMPLE_DRAFT });
  const post = (body: unknown): Request =>
    new Request("http://localhost/api/v1/review", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const response = await createReviewHandler(deps).POST(post(request));
  if (response.status !== 200) throw new Error(`API doc: the example request returned HTTP ${response.status}`);
  const result = ReviewResultSchema.parse(await response.json());
  const errorResponse = await createReviewHandler(deps).POST(post({ text: "" }));
  const errorExample = ApiErrorSchema.parse(await errorResponse.json());
  const health = HealthSchema.parse(await createHealthHandler(deps).GET(new Request("http://localhost/api/v1/health")).json());

  const reasonRows = [
    ...Object.entries(REASON_CODES).flatMap(([status, codes]) => codes.map((c) => [`\`${status}\``, `\`${c}\``])),
    ["`ERROR`", "`INTERNAL_ERROR`"],
  ];

  const parts = [
    `# Azw API v1`,
    `> Generated by \`npm run docs:api\` (\`scripts/make-api-doc.ts\`) from the zod schemas in
> \`src/core/types.ts\`, the limits in \`src/core/review.ts\` and \`src/server/api-config.ts\`, and the
> strings in \`src/i18n/ar.ts\`. Do not edit by hand: \`npm test\` fails when this file differs from
> what the script produces. Corpus version of the examples: \`${result.corpusVersion}\`.`,
    `Azw is an AI-assisted tool, not a human scholar. It reports whether a quoted text stands in a
source with this wording. It never grades a hadith, interprets a verse or issues a ruling.`,

    `## POST /api/v1/review`,
    `Reviews one draft. The draft is not stored and not logged. When an LLM is configured on the server,
the draft is sent to its provider for the extraction of the quotes (\`docs/PRIVACY.md\`).`,
    `### Request`,
    `\`Content-Type: application/json\`. The body:`,
    schemaBlock(ReviewRequestSchema),
    table(
      ["Limit", "Default", "Set by"],
      [
        ["Length of `text`, in UTF-16 code units (JavaScript `String.length`)", String(API_DEFAULTS.MAX_DRAFT_CHARS), "`MAX_DRAFT_CHARS`"],
        ["Requests per client per minute", String(API_DEFAULTS.RATE_LIMIT_PER_MIN), "`RATE_LIMIT_PER_MIN`"],
        ["Items per draft (then the warning `ITEM_LIMIT_REACHED`)", String(REVIEW_LIMITS.MAX_ITEMS_PER_DRAFT), "`REVIEW_LIMITS` in `src/core/review.ts`"],
        ["Occurrences shown as evidence per item", String(REVIEW_LIMITS.MAX_EVIDENCE_PER_ITEM), "`REVIEW_LIMITS` in `src/core/review.ts`"],
      ],
    ),
    `### Response: 200`,
    `A \`ReviewResult\`. It is validated against this schema before it is sent; a result that fails is
answered with HTTP 500 and never in part.`,
    schemaBlock(ReviewResultSchema),
    `The schema cannot express two rules that the server also enforces: an item with status \`MATCH\`
has evidence and every evidence record is \`reviewed\`; an item with status \`ERROR\` has no evidence
and no explanation.`,
    `**What a client may show as source text.** Only \`evidence[].record.exactText\`, with
\`record.citation.display\`. A record carries no search text. \`grade\` is present only when the source
data has one for that record, and is shown with its \`by\`. \`explanation\`, when present, is generated
text and must be labeled «${t("explanation.generatedLabel")}». \`reasonAr\` is a fixed sentence of the tool, not
source text.`,
    `**Spans and diffs.** \`span\`, \`citedReference.span\` and \`diff[].draft\` are \`[start, end)\` offsets
into the request's \`text\`, in UTF-16 code units. \`diff[].source\` is \`[start, end)\` in the
\`exactText\` of the record \`recordId\`. A diff op carries ranges, never text.`,
    `**Coverage.** \`coverage\` lists the collections that were searched for this result. A collection
the corpus holds but no matcher searches yet is not listed, and no sentence names it.`,
    `**Evidence.** One entry per source record. A quote found in several places gives the entries of at
most ${REVIEW_LIMITS.MAX_EVIDENCE_PER_ITEM} occurrences; \`reasonAr\` states how many other places there are.`,
    `**Corrections.** An evidence entry of a \`DIFFERS\` item may carry \`correction\`: a change the writer
may choose to make. A client that applies it puts \`correction.text\` in place of
\`text.slice(correction.draft.start, correction.draft.end)\` and changes nothing else. For
\`target: "wording"\`, \`text\` is a stretch of that record's \`exactText\`; for \`target: "reference"\` it is
the record's \`citation.display\`, inside the brackets of the reference the draft cites. A client
never applies one unasked, and applies at most one per item (the entries of one item are other
places of the same quote). The ranges of different items never overlap. An entry without
\`correction\` offers none: the tool does not say which text or which reference is meant.`,
    `#### Statuses`,
    table(["`status`", "Label (ar)"], STATUSES.map((status) => [`\`${status}\``, t(`status.${status}`)])),
    `#### Reason codes`,
    table(["`status`", "`reasonCode`"], reasonRows),
    `#### Warnings`,
    table(["`warnings[]`", "Meaning"], Object.values(WARNINGS).map((w) => [`\`${w}\``, WARNING_NOTES[w]])),
    `### Errors`,
    `Every response that is not a \`ReviewResult\` has this body. It never has \`items\`.`,
    schemaBlock(ApiErrorSchema),
    table(
      ["HTTP", "`error.code`", "`error.message`"],
      API_ERROR_CODES.map((c) => [String(API_ERROR_HTTP_STATUS[c]), `\`${c}\``, ar[`api.error.${c}` as MessageKey]]),
    ),
    `\`{max}\` is the configured length limit. A 429 carries \`Retry-After\` (seconds).`,
    `### Headers`,
    table(
      ["Header", "Value"],
      [
        ["`Cache-Control`", "`no-store` on every response"],
        ["`X-Request-Id`", "The id the server logs for this request"],
        ["`Vary`", "`Origin`"],
      ],
    ),
    `### CORS`,
    `A request from the API's own origin, or with no \`Origin\` header, is served. A request from another
origin is served only when that origin is listed in \`CORS_ALLOWLIST\` (comma-separated origins; empty
by default; \`*\` is not accepted); it then gets \`Access-Control-Allow-Origin\` with that origin, and
its preflight (\`OPTIONS\`) is answered with 204. Any other origin gets 403 \`ORIGIN_NOT_ALLOWED\` and no
CORS header.`,
    `### Example`,
    `Request:`,
    jsonBlock(request),
    `Response (200), from a run on corpus \`${result.corpusVersion}\`:`,
    jsonBlock(result),
    `An error (400):`,
    jsonBlock(errorExample),

    `## GET /api/v1/health`,
    `200 when the corpus loads, 503 (\`ok: false\`, \`corpusVersion: null\`) when it does not.
\`llmConfigured\` says that the three \`LLM_*\` variables are set, not that an LLM took part in a
review: a result without the warning \`LLM_UNAVAILABLE_REGEX_ONLY\` says that.`,
    schemaBlock(HealthSchema),
    `Example:`,
    jsonBlock(health),
  ];
  return parts.join("\n\n") + "\n";
}
